from operator import itemgetter


def coords_string_to_tuple_list(coords_string: str) -> [(int, int)]:
    """
    A function that transforms string with coordinates of 2D points
    to list of tuples.

    Example of 2D coordinate string:
        "1,1 2,2 3,3 4,4 ..."

    Example of list of tuples:
         [(1,1), (2,2), (3,3), (4,4), ...]

    :type coords_string:  String
    :param coords_string: String with coordinates of 2D points
    :return:              A list of int tuples
    """

    str_2d_points = coords_string.split(" ")
    return [(int(str_2d_point.split(",")[0]), int(str_2d_point.split(",")[1]))
            for str_2d_point in str_2d_points]


def tuple_list_to_coords_string(tuple_list: [(int, int)]) -> str:
    """
    Inverse function to coords_string_to_tuple_list() that transforms a list
    of integer tuples to string.

    Example of integer tuples:
        [(1,1), (2,2), (3,3), (4,4), ...]

    Example of the output string:
        "1,1 2,2 3,3 4,4 ..."

    :type tuple_list:   List of integer tuples
    :param tuple_list:  List of integer tuples
    :return:            String that contains the transformed list of integer tuples
    """

    return " ".join([str(number_fst) + "," + str(number_nd)
                     for number_fst, number_nd in tuple_list])


def get_multiple_values_from_dict(dict: {}, keys: []) -> []:
    """
    Returns multiple values from dictionary with a single call.

    :param dict:  A dictionary that contains the wanted values.
    :param keys:  Keys that should be used to find the values in
                  the dictionary.
    :return:      A list with the wanted values.
    """
    if not keys:
        return []

    values = itemgetter(*keys)(dict)

    if type(values) is tuple:
        return list(values)
    else:
        return [values]


def range_wrapper(start_value: int, end_value: int) -> [int]:
    """
    Wrapper around builtin function range(). The function returns
    start_value when start_value == end_value.

    :param start_value: Start value for range()
    :param end_value:   End value for range()
    :return:            List of integers generated by range()
    """
    return list(range(start_value, end_value)) + [end_value]
