from table_recognition.graph.colorers.output import OutputGraphColorer
from table_recognition.graph.colorers.basic_graph_colorer import BasicGraphColorer
from table_recognition.graph.colorers.geometry_graph_colorer import GeometryGraphColorer
